name: Trigger Manual (Dispatch)
on:
  workflow_dispatch:
    inputs:
      nivel_alerta:
        description: 'Nivel de alerta'
        required: true
        default: 'Informativo'
        type: choice
        options:
          - Informativo
          - Advertencia
          - Critico
jobs:
  imprimir:
    runs-on: ubuntu-latest
    steps:
      - run: echo "El nivel seleccionado es ${{ github.event.inputs.nivel_alerta }}"